### ISSUE TITLE
How to define ruby dependencies in brew?

### ISSUE THREAD

**Issue by brejoc** [sportngin/brew-gem#18]
Would it be possible to tell homebrew to treat e.g. fpm (a rubygem) as a dependency that can only be statisfied through brew-gem? Normally dependencies would be defined with `depends_on`, but I'm not sure how this should work.

**Comment by anfleene** [comment]
Do you mean list a brew-gem as a dependency of a non brew-gem package? We've never looked into that. brew-gem will install all of a gem's dependencies it just use the gemspec. But as a dep of a non brew-gem package my assumption is that it wouldn't work without work since thats a use case we've never tried.

**Comment by brejoc** [comment]
@anfleene That is right what I had in Mind. With basalt we are making use of invoke (Python) and fpm (Ruby). It would be really nice, if we could sort of create a meta-recipe with dependencies into the python and ruby world.

**Comment by anfleene** [comment]
I'm not seeing an easy way to do this inside of brew gem. Did you try specifying a [ruby dep](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#specifying-gems-python-modules-go-projects-etc-as-dependencies)?

```ruby
class Foo < Formula
  depends_on "mg" => :ruby
  depends_on "json" => :python
  depends_on "Authen::NTLM" => :perl
end
```

**Comment by brejoc** [comment]
If everything else fails, this would be the way to go. But I'd like to avoid having dependencies that need manual interaction with two different installers. Wouldn't it be possible to place the (brew gem) recipe for fpm in the tap and define both brew-gem and fpm as dependencies?

**Comment by anfleene** [comment]
Yeah, I think that would work. But because the formulas are dynamically generated at install time, if that dep wasn't met it wouldn't know where to get it.
