### ISSUE TITLE
brew gem install bundler not linking correct files

### ISSUE THREAD

**Issue by derimagia** [sportngin/brew-gem#20]
gem install bundler allows for "bundle" and "bundler" to be run but sadly running it through brew-gem doesn't work. It looks like it may have something to do with them being in "exe" directories:

https://github.com/bundler/bundler

**Comment by anfleene** [comment]
Hmm. Yup you are correct. It's not linking because it uses a different name for it's bindir. We should be able to look up the gem's bindir using the gemspec so I think we can fix this. Want to take a shot at it?

`Gem::Specification::load("GEM_NAME.gemspec").bindir` should give us what we want.

**Comment by Derimagia** [comment]
It looks like "cocoapods" has the same issue as well. I'm not very well-versed in ruby sadly. Hopefully I'll find the time to take a look.

**Comment by nicksieger** [comment]
Fixed by #26
