### ISSUE TITLE
Request for reopening of issue #25

### ISSUE THREAD

**Issue by AmirIHz** [sportngin/brew-gem#27]
Issue #25 has been closed, however, the issue has not been resolved. Could you please reopen the issue. I have added a comment: https://github.com/sportngin/brew-gem/issues/25#issuecomment-220072317 explaining why the issue has not been resolved.

_Once issue #25 has been reopened, this issue (request for reopening of issue #25) can be closed._

**Comment by anfleene** [comment]
Please do not open issues asking to reopen other issues. Communication can continue on a closed issue.

**Comment by AmirIHz** [comment]
This was the only way to get someone's attention as the closed issue seemed to have been abandoned. At any rate I opened this issue referring to the closed one based on the following suggestion:

http://stackoverflow.com/a/21333938

> Github has very simple rights/privileges (and even simpler management for them).
> 
> If you are not a collaborator of a repo, then (in regards to issues)
> 
> - you can open issues
> - you can comment on all existing issues (open or closed)
> - you can close your own issues
> - you can re-open your own issues *if you closed them yourself
> - you cannot close or re-open issues opened by someone else
> - you cannot re-open your own issues if a repo collaborator closed them
> 
> The situation you report falls in the last case, so you cannot reopen it. You can ask in the issue thread if a repo collaborator can reopen it, or **you can open a new issue and reference the old one (by mentioning its number preceded by a hash sign, e.g. #123).**
