### ISSUE TITLE
Use homebrew variables for binary path instead of hardcoding

### ISSUE THREAD

**Issue by paulhybryant** [sportngin/brew-gem#33]
I didn't install homebrew in /usr/local/

So the following line causes failure when installing
rubybindir = '<%= use_homebrew_ruby ? "/usr/local/bin" : "/usr/bin" %>'

**Comment by nicksieger** [comment]
@paulhybryant Thanks for reporting this. Can you try installing with `brew install brew-gem --HEAD` and see if the fix works for you?

**Comment by paulhybryant** [comment]
no, this is the error:

(erb):40:in `expand_formula': uninitialized constant Brew::Gem::CLI::HOMEBREW_PREFIX (NameError)
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/erb.rb:864:in `eval'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/erb.rb:864:in `result'
	from /usr/local/lib/brew/gem/cli.rb:49:in `expand_formula'
	from /usr/local/lib/brew/gem/cli.rb:56:in `block in with_temp_formula'
	from /usr/local/lib/brew/gem/cli.rb:55:in `open'
	from /usr/local/lib/brew/gem/cli.rb:55:in `with_temp_formula'
	from /usr/local/lib/brew/gem/cli.rb:76:in `run'
	from /usr/local/bin/brew-gem:7:in `<main>'

**Comment by nicksieger** [comment]
Ah, right. `brew-gem` gets launched by Homebrew rather than loaded inside of it. I think the fix should be to replace `HOMEBREW_PREFIX` with either `brew --prefix` or `ENV['HOMEBREW_PREFIX']`. I'll see which one works best.

**Comment by nicksieger** [comment]
@paulhybryant try the most recent master. Should work better now.

**Comment by paulhybryant** [comment]
yeah that works. Thanks @nicksieger

**Comment by paulhybryant** [comment]
This seems still only available in HEAD, not in a release?
