### ISSUE TITLE
Autodetect or configurable Ruby path

### ISSUE THREAD

**Issue by lkraider** [sportngin/brew-gem#38]
Based on #28, currently the user has to pass "`--homebrew-ruby`" for every `brew gem` command in case they are using a custom Ruby install.

This request is for the default Ruby path be auto-detected from the `PATH` environment variable, or otherwise be configurable (`~/.brew_gem`) so that the flag can be omitted.

**Comment by jasonkarns** [comment]
Perhaps this is closed now that #53 has landed?

**Comment by anfleene** [comment]
Closing fixed in #53
